### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'on_delete'

### ISSUE THREAD

**Issue by Ajinkz** [quakig/django-haystack-elasticsearch#2]
Got this error

>`python manage.py makemigrations`

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "d:\ProgramData\Anaconda3\envs\jango\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "d:\ProgramData\Anaconda3\envs\jango\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    django.setup()
  File "d:\ProgramData\Anaconda3\envs\jango\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "d:\ProgramData\Anaconda3\envs\jango\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "d:\ProgramData\Anaconda3\envs\jango\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "d:\ProgramData\Anaconda3\envs\jango\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Infogen\Desktop\django-haystack-elasticsearch-master\searchDemo\models.py", line 11, in <module>
    class Product(models.Model):
  File "C:\Users\Infogen\Desktop\django-haystack-elasticsearch-master\searchDemo\models.py", line 16, in Product
    category = models.ForeignKey(Category, related_name='category')
TypeError: __init__() missing 1 required positional argument: 'on_delete'

**Comment by bhaskar-c** [comment]
Yes this pertains to an old version of Django. Now django requires `on_delete` for all foreign keys.

Replace the line: 

`category = models.ForeignKey(Category, related_name='category')`

with

`category = models.ForeignKey(Category, related_name='category', on_delete=models.CASCADE)`

and it should work.

**Comment by bhaskar-c** [comment]
Closing as no reply and is likely solved
